# Generated by Django 4.2.14 on 2024-07-19 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Done', True), ('Pending', False)], max_length=10)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
