# Generated by Django 4.2.14 on 2024-07-19 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 15, 37, 4, 928369)),
        ),
    ]
