# Generated by Django 4.2.14 on 2024-07-26 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_tasks_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='tasks',
            name='timeOf_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 11, 13, 1, 556105)),
        ),
        migrations.AddField(
            model_name='tasks',
            name='timeOf_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 11, 13, 1, 556105)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
