# Generated by Django 4.2.14 on 2024-07-26 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_tasks_datetime_tasks_timeof_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 12, 9, 38, 23526)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 12, 9, 38, 23526)),
        ),
    ]
