# Generated by Django 4.2.14 on 2024-07-26 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_tasks_status_alter_tasks_timeof_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Done', True), ('Pending', False)], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 12, 15, 37, 214597)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 12, 15, 37, 214597)),
        ),
    ]
