# Generated by Django 4.2.14 on 2024-07-30 05:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0014_alter_tasks_status_alter_tasks_timeof_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 11, 9, 39, 896780)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 11, 9, 39, 896780)),
        ),
    ]
