# Generated by Django 4.2.14 on 2024-07-30 10:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0015_tasks_created_by_alter_tasks_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 16, 7, 28, 788414)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 16, 7, 28, 788414)),
        ),
        migrations.CreateModel(
            name='Activity_log',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('timeOf_creation', models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 30, 16, 7, 28, 788414), null=True)),
                ('timeOf_last_update', models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 30, 16, 7, 28, 788414), null=True)),
                ('action_performed', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
