# Generated by Django 4.2.14 on 2024-07-30 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_tasks_timeof_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_log',
            old_name='action_performed',
            new_name='nameOf_action_performed',
        ),
        migrations.AddField(
            model_name='activity_log',
            name='timeOf_action_performed',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 16, 10, 58, 691247)),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='timeOf_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 30, 16, 10, 58, 691247), null=True),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='timeOf_last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 30, 16, 10, 58, 691247), null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 16, 10, 58, 691247)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 16, 10, 58, 691247)),
        ),
    ]
