# Generated by Django 4.2.14 on 2024-07-30 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_rename_action_performed_activity_log_nameof_action_performed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_log',
            old_name='created_by',
            new_name='performed_by',
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='timeOf_action_performed',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 16, 18, 22, 319091)),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='timeOf_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 30, 16, 18, 22, 319091), null=True),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='timeOf_last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 30, 16, 18, 22, 319091), null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 16, 18, 22, 319091)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 16, 18, 22, 319091)),
        ),
    ]
