# Generated by Django 4.2.14 on 2024-08-05 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_rename_created_by_activity_log_performed_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_log',
            old_name='performed_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='id',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='timeOf_action_performed',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 12, 38, 53, 209011)),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='timeOf_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='timeOf_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 12, 38, 53, 209011)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 12, 38, 53, 209011)),
        ),
    ]
