# Generated by Django 4.2.14 on 2024-08-05 09:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0019_rename_performed_by_activity_log_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_log',
            old_name='nameOf_action_performed',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='activity_log',
            name='timeOf_action_performed',
        ),
        migrations.AddField(
            model_name='activity_log',
            name='timeOf_action',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 14, 30, 44, 231036)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 14, 30, 44, 231036)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 14, 30, 44, 231036)),
        ),
        migrations.CreateModel(
            name='User_log',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
