# Generated by Django 4.2.14 on 2024-08-05 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_user_log_timeof_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='timeOf_action',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 15, 3, 48, 427668)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 15, 3, 48, 427668)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 15, 3, 48, 427668)),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='timeOf_action',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 15, 3, 48, 443291)),
        ),
    ]
