# Generated by Django 4.2.14 on 2024-08-07 04:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0022_alter_activity_log_timeof_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='timeOf_action',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 10, 13, 58, 455035)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 10, 13, 58, 455035)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timeOf_last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 10, 13, 58, 455035)),
        ),
        migrations.AlterField(
            model_name='user_log',
            name='timeOf_action',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 10, 13, 58, 455035)),
        ),
        migrations.CreateModel(
            name='Session_time',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
